FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

#RUN useradd -m app
#RUN chown -R app:app /usr/local/bin/jupyter
#USER app

# check this set up for server
# https://jupyter-notebook.readthedocs.io/en/stable/public_server.html
EXPOSE 8888
#CMD jupyter notebook --no-browser --allow-root --generate-config
CMD jupyter lab --allow-root
