FROM python:3

RUN pip install notebook jupyterlab

#RUN useradd -m app
#RUN chown -R app:app /usr/local/bin/jupyter
#USER app

WORKDIR /notebook

# check this set up for server
# https://jupyter-notebook.readthedocs.io/en/stable/public_server.html
EXPOSE 8888
#CMD jupyter notebook --no-browser --allow-root --generate-config
CMD jupyter lab --allow-root
